// Usage: https://github.com/Huachao/vscode-restclient/blob/master/README.md#usage

### Get all contacts of the phonebook
GET http://localhost:3001/api/persons HTTP/1.1

### Get certain contact of the phonebook by id
GET http://localhost:3001/api/persons/1 HTTP/1.1

### Delete certain contact of the phonebook by id
DELETE http://localhost:3001/api/persons/1 HTTP/1.1